spring:
  config:
    activate:
      on-profile: local
  flyway:
    locations: classpath:db/migration,classpath:db/local

tizo:
  cors:
    allowed-origins: ${TIZO_CORS_ALLOWED_ORIGINS:http://localhost:4200}
  demo:
    enabled: true

logging:
  level:
    com.tizo.ecommerce: DEBUG
